pipeline {
    
    agent any
    
    stages{
        stage('build'){
            steps{
                sh ' echo "Build is successful at build from GITHUB"'
            }
        }
        
        
        stage('test'){
            steps{
                sh ' echo "Build is successful at test from GITHUB"'
            }
        }

        stage('deploy'){
            steps{
                sh ' echo "Build is successful at deploy"'
            }
        }
    }
}
